spring.application.name=demo
server.port=8080
logging.level.com.guild.demo=INFO

spring.datasource.url=jdbc:postgresql://localhost:5432/guild_db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true